In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [59]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.sample()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3847,8439-LTUGF,Male,0,No,No,10,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Credit card (automatic),20.0,198.6,No

In [60]:
df.shape

(7043, 21)

In [61]:
df['customerID'].unique()

array(['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', ..., '4801-JZAZL',
       '8361-LTMKD', '3186-AJIEK'], shape=(7043,), dtype=object)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [63]:
df['TotalCharges'].sample(10)

6290    6585.35
2560     4154.8
1433     593.85
4133    5581.05
1736       19.5
1414     3418.2
3429     1007.9
2757     5848.6
6778       1567
2782       3297
Name: TotalCharges, dtype: object

In [64]:
pd.to_numeric(df['TotalCharges'])

ValueError: Unable to parse string " " at position 488

In [65]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [66]:
print(df.iloc[488])

customerID                         4472-LVYGI
gender                                 Female
SeniorCitizen                               0
Partner                                   Yes
Dependents                                Yes
tenure                                      0
PhoneService                               No
MultipleLines                No phone service
InternetService                           DSL
OnlineSecurity                            Yes
OnlineBackup                               No
DeviceProtection                          Yes
TechSupport                               Yes
StreamingTV                               Yes
StreamingMovies                            No
Contract                             Two year
PaperlessBilling                          Yes
PaymentMethod       Bank transfer (automatic)
MonthlyCharges                          52.55
TotalCharges
Churn                                      No
Name: 488, dtype: object

In [67]:
round((df['TotalCharges'] == " ").sum())

11

In [68]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [69]:
df['TotalCharges'] = df['TotalCharges'].replace(" ","0.0")

In [70]:
round((df['TotalCharges'] == " ").sum())

0

In [71]:
pd.to_numeric(df['TotalCharges'])

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [72]:
df['TotalCharges'].dtype

dtype('O')

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [74]:
df.sample()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3280,6504-VBLFL,Male,0,Yes,No,55,Yes,No,DSL,Yes,...,Yes,No,No,No,Two year,No,Electronic check,58.6,3068.6,No

In [75]:
df['Churn'].value_counts(normalize=True) * 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [76]:
from sklearn.model_selection import train_test_split
x = df.drop(columns = ['customerID','Churn'])
y = df['Churn']

X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42,stratify=y)

print(f"X_train shape : {X_train.shape}")
print(f"X_test shape : {X_test.shape}")

print("\n--- Training Set Class Ratio (%) ---")
print(y_train.value_counts(normalize=True) * 100)

print("\n--- Testing Set Class Ratio (%) ---")
print(y_test.value_counts(normalize=True) * 100)

X_train shape : (5634, 19)
X_test shape : (1409, 19)

--- Training Set Class Ratio (%) ---
Churn
No     73.464679
Yes    26.535321
Name: proportion, dtype: float64

--- Testing Set Class Ratio (%) ---
Churn
No     73.456352
Yes    26.543648
Name: proportion, dtype: float64

In [77]:
df.sample(12)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
6796,8450-JOVAH,Male,0,Yes,Yes,2,Yes,Yes,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,56.70,113.55,Yes
819,4178-EGMON,Male,0,Yes,No,70,Yes,Yes,Fiber optic,Yes,...,No,Yes,No,No,Two year,Yes,Credit card (automatic),88.00,5986.45,No
1016,7649-SIJJF,Male,0,Yes,No,71,Yes,Yes,DSL,Yes,...,Yes,Yes,No,Yes,Two year,Yes,Mailed check,80.10,5585.4,No
1320,8947-YRTDV,Male,0,Yes,Yes,32,Yes,No,Fiber optic,Yes,...,Yes,No,No,Yes,One year,No,Mailed check,94.80,3131.55,No
6561,6339-YPSAH,Male,0,No,No,9,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.80,704.3,No
4955,5884-GCYMI,Male,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,No,Mailed check,69.40,69.4,Yes
2821,4102-OQUPX,Male,1,Yes,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.40,74.4,Yes
915,6513-EECDB,Male,1,Yes,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,73.55,73.55,Yes
2178,1657-DYMBM,Male,0,Yes,No,53,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),19.90,1110.05,No
315,5027-YOCXN,Male,0,Yes,Yes,51,Yes,Yes,Fiber optic,Yes,...,No,Yes,Yes,Yes,One year,No,Credit card (automatic),110.05,5686.4,No
2288,2135-DQWAQ,Female,0,No,No,5,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Mailed check,85.30,420.45,No
1967,0565-IYCGT,Male,0,No,No,69,Yes,Yes,DSL,Yes,...,Yes,Yes,No,Yes,One year,Yes,Credit card (automatic),78.60,5356.45,Yes

In [78]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [79]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# 1. Define Column Groups based on Data Types & Business Logic

# Numerical columns that need scaling
num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']

# Ordinal column with a natural order/hierarchy
ordinal_cols = ['Contract']

# Categorical columns with no order (nominal / binary)
# Note: SeniorCitizen is already 0/1 numeric, so it passes through unchanged
nominal_cols = [
    'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
    'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
    'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling',
    'PaymentMethod'
]

# 2. Define Sub-Pipelines for Each Feature Type

# Numerical Pipeline: Impute missing values (if any) -> Standard Scale
num_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Ordinal Pipeline: Explicitly define category rank
# Order: 'Month-to-month' (0) < 'One year' (1) < 'Two year' (2)
ordinal_pipeline = Pipeline(steps=[
    ('ordinal_encoder', OrdinalEncoder(
        categories=[['Month-to-month', 'One year', 'Two year']]
    ))
])

# Nominal Pipeline: One-Hot Encode (drop='first' prevents collinearity/dummy variable trap)
nominal_pipeline = Pipeline(steps=[
    ('onehot_encoder', OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore'))
])

# 3. Combine into a Single Master ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_pipeline, num_cols),
        ('ord', ordinal_pipeline, ordinal_cols),
        ('nom', nominal_pipeline, nominal_cols)
    ],
    remainder='passthrough'  # Keeps 'SeniorCitizen' as 0/1 without modification
)

print("Preprocessor Pipeline created successfully!")

Preprocessor Pipeline created successfully!

In [82]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [83]:
# Check data types
print("X_train dtype:", X_train['TotalCharges'].dtype)

X_train dtype: object

In [84]:
# Convert TotalCharges to float in both X_train and X_test
X_train['TotalCharges'] = pd.to_numeric(X_train['TotalCharges'], errors='coerce').fillna(0.0)
X_test['TotalCharges'] = pd.to_numeric(X_test['TotalCharges'], errors='coerce').fillna(0.0)

# Re-run the preprocessor fit_transform
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

print("Transformed X_train shape:", X_train_transformed.shape)
print("Transformed X_test shape:", X_test_transformed.shape)

Transformed X_train shape: (5634, 29)
Transformed X_test shape: (1409, 29)

In [85]:
# 1. Fit & Transform Feature Matrices
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

# 2. Encode Target Variable (Yes -> 1, No -> 0)
y_train_encoded = y_train.map({'Yes': 1, 'No': 0})
y_test_encoded = y_test.map({'Yes': 1, 'No': 0})

# 3. Get Feature Names post One-Hot Encoding
feature_names = preprocessor.get_feature_names_out()

# Verification
print("--- Final Preprocessed Data Shapes ---")
print(f"X_train_transformed: {X_train_transformed.shape}")
print(f"X_test_transformed:  {X_test_transformed.shape}")
print(f"Total features after One-Hot Encoding: {len(feature_names)}")

--- Final Preprocessed Data Shapes ---
X_train_transformed: (5634, 29)
X_test_transformed:  (1409, 29)
Total features after One-Hot Encoding: 29

In [86]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# 1. Initialize & Train Baseline Logistic Regression
baseline_model = LogisticRegression(max_iter=1000, random_state=42)
baseline_model.fit(X_train_transformed, y_train_encoded)

# 2. Predict on Test Data
y_pred = baseline_model.predict(X_test_transformed)
y_pred_proba = baseline_model.predict_proba(X_test_transformed)[:, 1]

# 3. Evaluate Performance
print("--- Classification Report ---")
print(classification_report(y_test_encoded, y_pred))

print(f"ROC-AUC Score: {roc_auc_score(y_test_encoded, y_pred_proba):.4f}")

print("\n--- Confusion Matrix ---")
print(confusion_matrix(y_test_encoded, y_pred))

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.65      0.56      0.60       374

    accuracy                           0.80      1409
   macro avg       0.75      0.72      0.74      1409
weighted avg       0.80      0.80      0.80      1409

ROC-AUC Score: 0.8423

--- Confusion Matrix ---
[[925 110]
 [166 208]]

In [87]:
# Train Logistic Regression with class_weight='balanced'
balanced_model = LogisticRegression(
    class_weight="balanced", max_iter=1000, random_state=42
)
balanced_model.fit(X_train_transformed, y_train_encoded)

# Predict on Test Data
y_pred_balanced = balanced_model.predict(X_test_transformed)
y_pred_proba_balanced = balanced_model.predict_proba(X_test_transformed)[:, 1]

# Evaluate Updated Performance
print("--- Balanced Classification Report ---")
print(classification_report(y_test_encoded, y_pred_balanced))

print(
    f"ROC-AUC Score: {roc_auc_score(y_test_encoded, y_pred_proba_balanced):.4f}"
)

print("\n--- Balanced Confusion Matrix ---")
print(confusion_matrix(y_test_encoded, y_pred_balanced))

--- Balanced Classification Report ---
              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.50      0.78      0.61       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

ROC-AUC Score: 0.8417

--- Balanced Confusion Matrix ---
[[747 288]
 [ 81 293]]

In [88]:
import pandas as pd
import numpy as np
import joblib
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score

# ==========================================
# 1. CUSTOM EDGE-CASE SAFE TRANSFORMERS
# ==========================================
class RawDataCleaner(BaseEstimator, TransformerMixin):
    """
    Handles raw payload sanitization & edge cases:
    - Replaces empty strings/spaces in TotalCharges with 0.0
    - Coerces numerical columns to correct dtypes
    - Drops ID column safely if present
    """
    def __init__(self, id_col='customerID'):
        self.id_col = id_col

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()
        if self.id_col in X.columns:
            X = X.drop(columns=[self.id_col])
        
        # Clean TotalCharges edge case (space strings like ' ')
        if 'TotalCharges' in X.columns:
            X['TotalCharges'] = pd.to_numeric(X['TotalCharges'], errors='coerce').fillna(0.0)
        if 'tenure' in X.columns:
            X['tenure'] = pd.to_numeric(X['tenure'], errors='coerce').fillna(0)
        if 'MonthlyCharges' in X.columns:
            X['MonthlyCharges'] = pd.to_numeric(X['MonthlyCharges'], errors='coerce').fillna(0.0)
            
        return X

# ==========================================
# 2. FEATURE PIPELINE DEFINITION
# ==========================================
def build_production_pipeline():
    num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
    ordinal_cols = ['Contract']
    nominal_cols = [
        'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
        'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
        'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling',
        'PaymentMethod'
    ]

    num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])

    ordinal_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('ordinal', OrdinalEncoder(
            categories=[['Month-to-month', 'One year', 'Two year']],
            handle_unknown='use_encoded_value', 
            unknown_value=-1
        ))
    ])

    nominal_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore'))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', num_pipeline, num_cols),
            ('ord', ordinal_pipeline, ordinal_cols),
            ('nom', nominal_pipeline, nominal_cols)
        ],
        remainder='passthrough'  # Keeps SeniorCitizen (0/1) intact
    )

    # Master End-to-End Pipeline
    full_pipeline = Pipeline([
        ('cleaner', RawDataCleaner()),
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(
            n_estimators=200,
            max_depth=10,
            class_weight='balanced',
            random_state=42,
            n_jobs=-1
        ))
    ])
    
    return full_pipeline

# ==========================================
# 3. TRAINING & EXPORT EXECUTION
# ==========================================
if __name__ == "__main__":
    # Load Raw Dataset
    df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
    
    X = df.drop(columns=['Churn'])
    y = df['Churn'].map({'Yes': 1, 'No': 0})

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )

    # Train Complete Pipeline directly on RAW data
    pipeline = build_production_pipeline()
    pipeline.fit(X_train, y_train)

    # Evaluate
    y_pred = pipeline.predict(X_test)
    y_proba = pipeline.predict_proba(X_test)[:, 1]
    
    print("--- PRODUCTION PIPELINE EVALUATION ---")
    print(classification_report(y_test, y_pred))
    print(f"ROC-AUC Score: {roc_auc_score(y_test, y_proba):.4f}")

    # Export Single Executable Artifact
    joblib.dump(pipeline, "churn_model_pipeline.joblib")
    print("Model Artifact successfully saved as 'churn_model_pipeline.joblib'")

--- PRODUCTION PIPELINE EVALUATION ---
              precision    recall  f1-score   support

           0       0.88      0.79      0.83      1035
           1       0.55      0.70      0.62       374

    accuracy                           0.77      1409
   macro avg       0.72      0.75      0.73      1409
weighted avg       0.79      0.77      0.78      1409

ROC-AUC Score: 0.8392
Model Artifact successfully saved as 'churn_model_pipeline.joblib'

In [89]:
import pandas as pd
import joblib

class ChurnPredictorService:
    def __init__(self, model_path="churn_model_pipeline.joblib"):
        # Load the single pipeline artifact containing cleaner, preprocessor, and model
        self.pipeline = joblib.load(model_path)
        self.required_columns = [
            'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
            'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
            'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
            'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
            'MonthlyCharges', 'TotalCharges'
        ]

    def predict(self, raw_input_dict: dict, threshold: float = 0.40) -> dict:
        """
        Takes raw API JSON input, validates fields, and returns prediction with risk assessment.
        """
        try:
            # Convert dictionary payload to DataFrame
            df_input = pd.DataFrame([raw_input_dict])

            # Edge Case Guard: Check missing required keys
            for col in self.required_columns:
                if col not in df_input.columns:
                    df_input[col] = np.nan

            # Predict Probability using loaded pipeline
            churn_probability = float(self.pipeline.predict_proba(df_input)[0, 1])
            
            # Custom Decision Threshold for High Recall in Business Context
            churn_prediction = int(churn_probability >= threshold)

            return {
                "status": "success",
                "churn_prediction": "Yes" if churn_prediction == 1 else "No",
                "churn_probability": round(churn_probability, 4),
                "risk_level": "High" if churn_probability >= 0.6 else ("Medium" if churn_probability >= 0.4 else "Low")
            }

        except Exception as e:
            return {
                "status": "error",
                "message": f"Inference pipeline failed: {str(e)}"
            }

# ==========================================
# TEST INFERENCE WITH RAW/DIRTY JSON PAYLOAD
# ==========================================
if __name__ == "__main__":
    predictor = ChurnPredictorService()

    # Raw dirty payload with edge cases (TotalCharges is blank space, missing customerID)
    sample_payload = {
        "gender": "Female",
        "SeniorCitizen": 0,
        "Partner": "Yes",
        "Dependents": "No",
        "tenure": 0,
        "PhoneService": "No",
        "MultipleLines": "No phone service",
        "InternetService": "DSL",
        "OnlineSecurity": "No",
        "OnlineBackup": "Yes",
        "DeviceProtection": "No",
        "TechSupport": "No",
        "StreamingTV": "No",
        "StreamingMovies": "No",
        "Contract": "Month-to-month",
        "PaperlessBilling": "Yes",
        "PaymentMethod": "Electronic check",
        "MonthlyCharges": 29.85,
        "TotalCharges": " "  # CRASH TEST: Blank space string
    }

    result = predictor.predict(sample_payload)
    print("API Prediction Output:")
    print(result)

API Prediction Output:
{'status': 'success', 'churn_prediction': 'Yes', 'churn_probability': 0.6223, 'risk_level': 'High'}

In [92]:
import joblib

# 'pipeline' ki jagah apne trained pipeline variable ka naam rakhein
joblib.dump(pipeline, 'churn_model_pipeline.joblib')

['churn_model_pipeline.joblib']

In [91]:
!git init
!git branch -M main
!git remote add origin https://github.com/Rohitcd-47/Data-Science-Journey.git
!git add .
!git commit -m "Add Telco Churn app files"
!git push -u origin main --force

Initialized empty Git repository in C:/Users/Admin/100-Days-Machine-Learning/Projects/CustomerChurn-Pipeline-System/.git/

warning: in the working copy of '.ipynb_checkpoints/Customer-churn-intelligence-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/app-checkpoint.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/requirements-checkpoint.txt', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Customer-churn-intelligence.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'app.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'requirements.txt', LF will be replaced by CRLF the next time Git touches it

[main (root-commit) 1fbbab9] Add Telco Churn app files
 7 files changed, 9390 insertions(+)
 create mode 100644 .ipynb_checkpoints/Customer-churn-intelligence-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/app-checkpoint.py
 create mode 100644 .ipynb_checkpoints/requirements-checkpoint.txt
 create mode 100644 Customer-churn-intelligence.ipynb
 create mode 100644 WA_Fn-UseC_-Telco-Customer-Churn.csv
 create mode 100644 app.py
 create mode 100644 requirements.txt
branch 'main' set up to track 'origin/main'.

To https://github.com/Rohitcd-47/Data-Science-Journey.git
 + c3ba6ca...1fbbab9 main -> main (forced update)

In [93]:
!git add .
!git commit -m "Add joblib model file"
!git push origin main

warning: in the working copy of 'Customer-churn-intelligence.ipynb', LF will be replaced by CRLF the next time Git touches it

[main e46ac27] Add joblib model file
 2 files changed, 67 insertions(+)
 create mode 100644 churn_model_pipeline.joblib

To https://github.com/Rohitcd-47/Data-Science-Journey.git
   1fbbab9..e46ac27  main -> main

In [94]:
import os

# Parent directory mein jane ke liye:
os.chdir('../../../')  # Ye aapko main repo level par le jayega
print("Current Working Directory:", os.getcwd())

Current Working Directory: C:\Users\Admin

In [95]:
import os

# Main repository folder mein jao
os.chdir(r"C:\Users\Admin\100-Days-Machine-Learning")
print("Current Working Directory:", os.getcwd())

Current Working Directory: C:\Users\Admin\100-Days-Machine-Learning

In [96]:
!git init
!git branch -M main
!git remote remove origin
!git remote add origin https://github.com/Rohitcd-47/Data-Science-Journey.git
!git add .
!git commit -m "Restore all main folders and churn project"
!git push -u origin main --force

Initialized empty Git repository in C:/Users/Admin/100-Days-Machine-Learning/.git/

error: No such remote: 'origin'
warning: in the working copy of 'Lecture-15/.ipynb_checkpoints/14_Workingwith_csv-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-15/.ipynb_checkpoints/aug_train-checkpoint.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-15/14_Workingwith_csv.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-15/aug_train.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/.ipynb_checkpoints/Practice question-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/.ipynb_checkpoints/Working-with-JSON-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/.ipynb_checkpoints/q1_junk_header-checkpoint.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/Practice question.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/Working-with-JSON.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/q10_nested_orders.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/q1_junk_header.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/q2_wrapped_results.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/q4_mixed_dates.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/q5_bad_encoding.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/q9_missing_fields.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-16/train.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-17/.ipynb_checkpoints/Crickbuzz-API-Dataset-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-17/.ipynb_checkpoints/Movies-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-17/.ipynb_checkpoints/Pulling data from API-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-17/Crickbuzz-API-Dataset.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-17/Movies.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-17/Pulling data from API.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-18/.ipynb_checkpoints/Web-scraping-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-18/Web-scraping.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-19/.ipynb_checkpoints/Understand your data-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-19/Understand your data.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-20/.ipynb_checkpoints/EDA_using_Univariate-analysis-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-20/EDA_using_Univariate-analysis.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-21/.ipynb_checkpoints/EDA-Practice-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-21/EDA-Practice.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-22/.ipynb_checkpoints/Pandas-Profiling-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-22/.ipynb_checkpoints/PandasProfiling_on_CafeSales-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-22/Pandas-Profiling.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-22/PandasProfiling_on_CafeSales.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-23/.ipynb_checkpoints/Feature-Scaling-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-23/Feature-Scaling.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-23/house_price_data.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-23/loan_default_data.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-27/.ipynb_checkpoints/One-Hot-Encoding-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-27/One-Hot-Encoding.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-27/cars.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-28/.ipynb_checkpoints/Column-Transformer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-28/.ipynb_checkpoints/PracticeSet-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-28/Column-Transformer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-28/PracticeSet.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-28/column_transformation_practice.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-30/.ipynb_checkpoints/Functional-Transformer-Practice-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-30/.ipynb_checkpoints/Functional-Transformer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-30/.ipynb_checkpoints/day30-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-30/Functional-Transformer-Practice.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-30/Functional-Transformer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-30/day30.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-31/.ipynb_checkpoints/Power-Transformer-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-31/Power-Transformer.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-33/.ipynb_checkpoints/Handling-mixed-value-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-33/Handling-mixed-value.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-35/.ipynb_checkpoints/Complete-Case-analysis-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-35/Complete-Case-analysis.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Lecture-35/data_science_job.csv', LF will be replaced by CRLF the next time Git touches it
warning: adding embedded git repository: Projects/CustomerChurn-Pipeline-System
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint: 	git submodule add <url> Projects/CustomerChurn-Pipeline-System
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint: 	git rm --cached Projects/CustomerChurn-Pipeline-System
hint:
hint: See "git help submodule" for more information.
hint: Disable this message with "git config set advice.addEmbeddedRepo false"
warning: in the working copy of 'Projects/German-Credit-Risk/.ipynb_checkpoints/e-commerce-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Projects/German-Credit-Risk/e-commerce.ipynb', LF will be replaced by CRLF the next time Git touches it

[main (root-commit) 503d7d8] Restore all main folders and churn project
 92 files changed, 1315195 insertions(+)
 create mode 100644 Lecture-15/.ipynb_checkpoints/14_Workingwith_csv-checkpoint.ipynb
 create mode 100644 Lecture-15/.ipynb_checkpoints/aug_train-checkpoint.csv
 create mode 100644 Lecture-15/14_Workingwith_csv.ipynb
 create mode 100644 Lecture-15/IPL Matches 2008-2020.csv
 create mode 100644 Lecture-15/aug_train.csv
 create mode 100644 Lecture-15/movie_titles_metadata.tsv
 create mode 100644 Lecture-15/test.csv
 create mode 100644 Lecture-15/zomato.csv
 create mode 100644 Lecture-16/.ipynb_checkpoints/Practice question-checkpoint.ipynb
 create mode 100644 Lecture-16/.ipynb_checkpoints/Working-with-JSON-checkpoint.ipynb
 create mode 100644 Lecture-16/.ipynb_checkpoints/q1_junk_header-checkpoint.csv
 create mode 100644 Lecture-16/Practice question.ipynb
 create mode 100644 Lecture-16/Working-with-JSON.ipynb
 create mode 100644 Lecture-16/q10_nested_orders.json
 create mode 100644 Lecture-16/q1_junk_header.csv
 create mode 100644 Lecture-16/q2_wrapped_results.json
 create mode 100644 Lecture-16/q4_mixed_dates.csv
 create mode 100644 Lecture-16/q5_bad_encoding.csv
 create mode 100644 Lecture-16/q6_large_transactions.csv
 create mode 100644 Lecture-16/q9_missing_fields.json
 create mode 100644 Lecture-16/train.json
 create mode 100644 Lecture-17/.ipynb_checkpoints/Crickbuzz-API-Dataset-checkpoint.ipynb
 create mode 100644 Lecture-17/.ipynb_checkpoints/IMDb Top 100 Movies-checkpoint.csv
 create mode 100644 Lecture-17/.ipynb_checkpoints/Language-checkpoint
 create mode 100644 Lecture-17/.ipynb_checkpoints/Movies-checkpoint.ipynb
 create mode 100644 Lecture-17/.ipynb_checkpoints/Pulling data from API-checkpoint.ipynb
 create mode 100644 Lecture-17/Crickbuzz-API-Dataset.ipynb
 create mode 100644 Lecture-17/IMDb Top 100 Movies.csv
 create mode 100644 Lecture-17/Language
 create mode 100644 Lecture-17/Movies.ipynb
 create mode 100644 Lecture-17/Pulling data from API.ipynb
 create mode 100644 Lecture-18/.ipynb_checkpoints/Web-scraping-checkpoint.ipynb
 create mode 100644 Lecture-18/.ipynb_checkpoints/ambitionbox_companies-checkpoint.csv
 create mode 100644 Lecture-18/Web-scraping.ipynb
 create mode 100644 Lecture-18/ambitionbox_companies.csv
 create mode 100644 Lecture-19/.ipynb_checkpoints/Understand your data-checkpoint.ipynb
 create mode 100644 Lecture-19/Understand your data.ipynb
 create mode 100644 Lecture-19/train.csv
 create mode 100644 Lecture-20/.ipynb_checkpoints/EDA_using_Univariate-analysis-checkpoint.ipynb
 create mode 100644 Lecture-20/EDA_using_Univariate-analysis.ipynb
 create mode 100644 Lecture-20/train.csv
 create mode 100644 Lecture-21/.ipynb_checkpoints/Cleaned-CafeSales-Data-checkpoint.csv
 create mode 100644 Lecture-21/.ipynb_checkpoints/EDA-Practice-checkpoint.ipynb
 create mode 100644 Lecture-21/Cleaned-CafeSales-Data.csv
 create mode 100644 Lecture-21/EDA-Practice.ipynb
 create mode 100644 Lecture-21/dirty_cafe_sales.csv
 create mode 100644 Lecture-22/.ipynb_checkpoints/Pandas-Profiling-checkpoint.ipynb
 create mode 100644 Lecture-22/.ipynb_checkpoints/PandasProfiling_on_CafeSales-checkpoint.ipynb
 create mode 100644 Lecture-22/.ipynb_checkpoints/cafe-checkpoint.html
 create mode 100644 Lecture-22/.ipynb_checkpoints/output-checkpoint.html
 create mode 100644 Lecture-22/Pandas-Profiling.ipynb
 create mode 100644 Lecture-22/PandasProfiling_on_CafeSales.ipynb
 create mode 100644 Lecture-22/cafe.html
 create mode 100644 Lecture-22/dirty_cafe_sales.csv
 create mode 100644 Lecture-22/output.html
 create mode 100644 Lecture-22/train.csv
 create mode 100644 Lecture-23/.ipynb_checkpoints/Feature-Scaling-checkpoint.ipynb
 create mode 100644 Lecture-23/Feature-Scaling.ipynb
 create mode 100644 Lecture-23/house_price_data.csv
 create mode 100644 Lecture-23/loan_default_data.csv
 create mode 100644 Lecture-27/.ipynb_checkpoints/One-Hot-Encoding-checkpoint.ipynb
 create mode 100644 Lecture-27/.ipynb_checkpoints/one_hot_encoding_post-checkpoint.png
 create mode 100644 Lecture-27/One-Hot-Encoding.ipynb
 create mode 100644 Lecture-27/cars.csv
 create mode 100644 Lecture-27/one_hot_encoding_post.png
 create mode 100644 Lecture-28/.ipynb_checkpoints/Column-Transformer-checkpoint.ipynb
 create mode 100644 Lecture-28/.ipynb_checkpoints/PracticeSet-checkpoint.ipynb
 create mode 100644 Lecture-28/Column-Transformer.ipynb
 create mode 100644 Lecture-28/PracticeSet.ipynb
 create mode 100644 Lecture-28/column_transformation_practice.csv
 create mode 100644 Lecture-28/covid_toy.csv
 create mode 100644 Lecture-30/.ipynb_checkpoints/Functional-Transformer-Practice-checkpoint.ipynb
 create mode 100644 Lecture-30/.ipynb_checkpoints/Functional-Transformer-checkpoint.ipynb
 create mode 100644 Lecture-30/.ipynb_checkpoints/day30-checkpoint.ipynb
 create mode 100644 Lecture-30/.ipynb_checkpoints/train-checkpoint.csv
 create mode 100644 Lecture-30/Functional-Transformer-Practice.ipynb
 create mode 100644 Lecture-30/Functional-Transformer.ipynb
 create mode 100644 Lecture-30/day30.ipynb
 create mode 100644 Lecture-30/train.csv
 create mode 100644 Lecture-31/.ipynb_checkpoints/Power-Transformer-checkpoint.ipynb
 create mode 100644 Lecture-31/Power-Transformer.ipynb
 create mode 100644 Lecture-33/.ipynb_checkpoints/Handling-mixed-value-checkpoint.ipynb
 create mode 100644 Lecture-33/Handling-mixed-value.ipynb
 create mode 100644 Lecture-33/titanic.csv
 create mode 100644 Lecture-35/.ipynb_checkpoints/Complete-Case-analysis-checkpoint.ipynb
 create mode 100644 Lecture-35/Complete-Case-analysis.ipynb
 create mode 100644 Lecture-35/data_science_job.csv
 create mode 160000 Projects/CustomerChurn-Pipeline-System
 create mode 100644 Projects/German-Credit-Risk/.ipynb_checkpoints/e-commerce-checkpoint.ipynb
 create mode 100644 Projects/German-Credit-Risk/.ipynb_checkpoints/ecommerce_returns-checkpoint.csv
 create mode 100644 Projects/German-Credit-Risk/e-commerce.ipynb
 create mode 100644 Projects/German-Credit-Risk/ecommerce_returns.csv
branch 'main' set up to track 'origin/main'.

To https://github.com/Rohitcd-47/Data-Science-Journey.git
 + e46ac27...503d7d8 main -> main (forced update)

In [97]:
!git add .
!git commit -m "Restore full Data Science Journey structure"
!git push -u origin main --force

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   Projects/CustomerChurn-Pipeline-System (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
branch 'main' set up to track 'origin/main'.

Everything up-to-date

In [98]:
import os
os.chdir(r"C:\Users\Admin\100-Days-Machine-Learning")
print("Current Working Directory:", os.getcwd())

Current Working Directory: C:\Users\Admin\100-Days-Machine-Learning

In [99]:
!git init
!git remote remove origin
!git remote add origin https://github.com/Rohitcd-47/Data-Science-Journey.git
!git add -A
!git commit -m "Restore original folder hierarchy with all lectures and projects"
!git push -u origin main --force

Reinitialized existing Git repository in C:/Users/Admin/100-Days-Machine-Learning/.git/
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   Projects/CustomerChurn-Pipeline-System (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
branch 'main' set up to track 'origin/main'.

Everything up-to-date

In [100]:
import os
print(os.listdir(r"C:\Users\Admin"))

['.anaconda', '.conda', '.continuum', '.copilot', '.cufflinks', '.eclipse', '.gemini', '.gitconfig', '.gradle', '.ipynb_checkpoints', '.ipython', '.jdks', '.junie', '.jupyter', '.m2', '.matplotlib', '.p2', '.streamlit', '.vscode', '.vscode-shared', '100-Days-Machine-Learning', '3D Objects', 'AI with Python', 'Anaacoda', 'anaconda3', 'AppData', 'Application Data', 'C-programming', 'Contacts', 'Cookies', 'Desktop', 'Documents', 'Downloads', 'eclipse', 'Favorites', 'Links', 'Local Settings', 'Microsoft', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Pictures', 'Plotlyandcufflinks.ipynb', 'Postman', 'PrintHood', 'Recent', 'Saved Games', 'scikit_learn_data', 'Searches', 'SendTo', 'Start Menu', 'Statistics & Probability', 'Templates', 'Untitled.ipynb', 'Videos', 'vscode-remote-wsl']