In [6]:
import pandas as pd
import numpy as np

perfect now give me all set of questions

Recognized request for independent practice questions
Recognized request for independent practice questions

Here's the full question set, questions only — attempt each one in your notebook using the files you just downloaded before checking the answers in the artifact.

Level 1 — Foundation

Q1. q1_junk_header.csv has 2 junk rows before the real header. Load only the actual data.

Q2. q2_wrapped_results.json wraps the real data inside a status/results envelope. Extract just the results into a flat DataFrame.

Q3. Fetch https://jsonplaceholder.typicode.com/users from the live API and load it into a DataFrame. Handle the case where the request fails.

Level 2 — Messy real data

Q4. q4_mixed_dates.csv has three different date formats in one column. Parse them all correctly into proper datetime values.

Q5. q5_bad_encoding.csv will throw a UnicodeDecodeError on a normal load. Figure out the actual encoding and load it without hardcoding the answer (detect it programmatically).

Q6. q6_large_transactions.csv is 500k rows. Without loading the whole thing into memory at once, compute the total amount grouped by category.

Q7. Hit https://api.github.com/users/torvalds/repos — this API paginates. Write code that pulls all pages, not just the first one, into a single DataFrame.

Q8. Hit the GitHub API repeatedly and fast enough to trigger a rate limit (403/429). Write retry logic that waits and retries instead of crashing.

Level 3 — Product-company level

Q9. q9_missing_fields.json has some records missing the phone key. Load it and produce a report of exactly which rows are missing which fields.

Q10. q10_nested_orders.json is nested two levels deep (user → orders → items). Flatten it into one row per item, with user and order id attached to every row.

Q11 (rapid fire — answer in one line each, out loud, like an interview):

read_json() vs json.load() + json_normalize() — when do you use which?
When would you reach for a service's SDK instead of raw requests?
Why check response.status_code before calling .json()?
CSV vs Parquet — when do you pick which, and why?

Q1. q1_junk_header.csv has 2 junk rows before the real header. Load only the actual data.

In [9]:
df = pd.read_csv('q1_junk_header.csv',skiprows=2)
df

   id    name  score
0   1   Alice     88
1   2     Bob     91
2   3  Chirag     76
3   4   Divya     95
4   5    Esha     67

Q2. q2_wrapped_results.json wraps the real data inside a status/results envelope. Extract just the results into a flat DataFrame.

In [11]:
df = pd.read_json('q2_wrapped_results.json')
df

  status  page                                   results
0     ok     1   {'id': 1, 'name': 'Alice', 'score': 88}
1     ok     1     {'id': 2, 'name': 'Bob', 'score': 91}
2     ok     1  {'id': 3, 'name': 'Chirag', 'score': 76}
3     ok     1   {'id': 4, 'name': 'Divya', 'score': 95}
4     ok     1    {'id': 5, 'name': 'Esha', 'score': 67}

In [13]:
flat_df = pd.DataFrame(df['results'].tolist())
flat_df

   id    name  score
0   1   Alice     88
1   2     Bob     91
2   3  Chirag     76
3   4   Divya     95
4   5    Esha     67

Q3. Fetch https://jsonplaceholder.typicode.com/users from the live API and load it into a DataFrame. Handle the case where the request fails.

In [15]:
df = pd.read_json('https://jsonplaceholder.typicode.com/users')
df

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

Q4. q4_mixed_dates.csv has three different date formats in one column. Parse them all correctly into proper datetime values.

In [17]:
df = pd.read_csv('q4_mixed_dates.csv')
df.head()

   id    name        date  amount
0   1   Alice  2024-01-05    2500
1   2     Bob  05/01/2024    3200
2   3  Chirag  Jan 5 2024    1800
3   4   Divya  2024-02-14    4100
4   5    Esha  14/02/2024    2900

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      6 non-null      int64
 1   name    6 non-null      object
 2   date    6 non-null      object
 3   amount  6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [19]:
df.head(2)

   id   name        date  amount
0   1  Alice  2024-01-05    2500
1   2    Bob  05/01/2024    3200

In [24]:
df['date'] = pd.to_datetime(df['date'], format='mixed', dayfirst=True)
df

   id    name       date  amount
0   1   Alice 2024-01-05    2500
1   2     Bob 2024-01-05    3200
2   3  Chirag 2024-01-05    1800
3   4   Divya 2024-02-14    4100
4   5    Esha 2024-02-14    2900
5   6  Farhan 2024-02-14    3300

Q5. q5_bad_encoding.csv will throw a UnicodeDecodeError on a normal load. Figure out the actual encoding and load it without hardcoding the answer (detect it programmatically).

In [38]:
!pip install chardet

Requirement already satisfied: chardet in c:\users\admin\anaacoda\lib\site-packages (5.2.0)

In [39]:
import chardet, pandas as pd

with open("q5_bad_encoding.csv", "rb") as f:
    raw = f.read()
result = chardet.detect(raw)
print(result)   # {'encoding': 'ISO-8859-1', 'confidence': ...}

df = pd.read_csv("q5_bad_encoding.csv", encoding=result["encoding"])
print(df)

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 4