In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('column_transformation_practice.csv')
df.head(5)

,ID,Name,Age,Gender,Department,Salary,Experience_Years,Join_Date,City,Remote
0,1,Person_1,56,Other,Tech,86661,23,2013-04-29,Hyderabad,Yes
1,2,Person_2,46,Other,Sales,61024,3,2014-03-12,Chennai,Yes
2,3,Person_3,32,Female,Marketing,100313,24,2019-06-03,Delhi,No
3,4,Person_4,25,Female,Tech,83006,20,2012-04-03,Kolkata,Yes
4,5,Person_5,38,Male,HR,45338,24,2012-07-17,Chennai,No

In [6]:
df.isnull().sum()

ID                  0
Name                0
Age                 0
Gender              0
Department          0
Salary              0
Experience_Years    0
Join_Date           0
City                0
Remote              0
dtype: int64

In [7]:
df['Gender'].value_counts()

Gender
Other     46
Male      42
Female    37
Name: count, dtype: int64

In [21]:
df.shape

(125, 10)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [14]:
df.sample(5)

,ID,Name,Age,Gender,Department,Salary,Experience_Years,Join_Date,City,Remote
2,3,Person_3,32,Female,Marketing,100313,24,2019-06-03,Delhi,No
44,45,Person_45,37,Male,HR,86556,6,2014-05-01,Kolkata,Yes
21,22,Person_22,38,Other,Marketing,103523,11,2019-12-17,Chennai,Yes
91,92,Person_92,52,Male,Tech,118223,5,2021-12-12,Kolkata,Yes
33,34,Person_34,24,Female,Tech,81990,24,2021-06-17,Kolkata,Yes

In [19]:
 transformer = ColumnTransformer(transformers=[
     ('tnf1',OneHotEncoder(sparse_output=False,drop='first',),['Gender','Department','City'])
 ],remainder='passthrough')

In [20]:

transformer.fit_transform(df).shape

(125, 18)

In [26]:
df.shape

(125, 10)

In [23]:
df['Department'].value_counts()

Department
HR           30
Sales        26
Marketing    25
Tech         24
Finance      20
Name: count, dtype: int64

In [24]:
df['City'].value_counts()

City
Delhi        24
Bangalore    23
Chennai      21
Mumbai       21
Kolkata      20
Hyderabad    16
Name: count, dtype: int64

In [25]:
df['Gender'].value_counts()

Gender
Other     46
Male      42
Female    37
Name: count, dtype: int64