In [1]:
import numpy as np
import pandas as pd

# Creating series

In [13]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'r':10,'o':20,'h':30}

In [14]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [15]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [16]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [27]:
pd.Series(d)

r    10
o    20
h    30
dtype: int64

# Creating a DataFrame

In [28]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [29]:
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [31]:
# without dictionary (without index)

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df1 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df1 = pd.DataFrame(data_list, columns=columns)
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selecting and indexing of columns

In [37]:
df1[["Name",'City','Age']]

    Name      City  Age
0   John  New York   28
1   Anna     Paris   34
2  Peter    Berlin   29
3  Linda    London   42

Creating a new column

In [39]:
df1["Designation"] = ["Doctor","Eng.","Doctor","Artist"]
df1

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000      Artist

Removing a column

In [44]:
# you have to provide the axis to remove it from dataframe
# x-axis = 0 
# y-axis = 1
df1.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [45]:
df1

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000      Artist

In [49]:
# but to remove or delete permanently you have to use 'inplace' keyword
#df1.drop('Designation',axis=1,inplace=True)
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [50]:
# for row deletion using axis=0

df.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [52]:
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting rows

In [53]:
# using loc
df1.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [54]:
# for selecting multiple rows
df1.loc[[0,1,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

Selecting subsets of rows and columns

In [60]:
df.loc[[0,1]] [["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [63]:
# exercise
df1.loc[[2,3]] [['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

I only want to see those people whose age is above 30

In [65]:
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [66]:
df[df['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

I only want poeple whose age is above 30 and their city must be paris

In [76]:
# when you are using multple conditions use parenthesis brackets

df[ (df1['Age']>30) & (df1['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Missing Data

1.Finding missing data

In [82]:

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [83]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [85]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [86]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

2. Removing missing data

In [87]:
# remove works with rows
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [88]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [90]:
# threshold check the no of non-null values in a row
# thresh = 3 means find 3 non-null values in a row
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

3. Filling the missing data

In [92]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [93]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [94]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [95]:
# filling with different values
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [96]:
# I want to fill with mean value

df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# Merging Joining and Concatenation

In [97]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [98]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [99]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

1. Merging

In [102]:
pd.merge(employees,salaries,on="employee_id",how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [103]:
pd.merge(employees,salaries,on="employee_id",how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [107]:
pd.merge(employees,salaries,on="employee_id",how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [108]:
pd.merge(employees,salaries,on="employee_id",how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

Concatination of 2 dataframes

In [109]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [111]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [112]:
# concat based on rows
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining 2 data frame**

In [114]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [115]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [116]:
df2

   score
2     85
3     90
4     75

In [117]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [118]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

# **Group By**

In [119]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [120]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [122]:
# Group by Category and calculate the sum of Sales
df.groupby('Category') ['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [123]:
# Group by Store and calculate the sum of Sales
store = df.groupby('Store') ['Sales'].sum()
store

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [124]:
# Group by multiple columns
# Group by Category and Store
df.groupby(['Category','Store']) ['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**Aggregation**

In [126]:
round(df['Sales'].mean())

188

In [129]:
round(df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median']))

sum       1500.0
mean       188.0
min        100.0
max        300.0
count        8.0
std         66.0
median     190.0
Name: Sales, dtype: float64

# **Pivot Tables**

In [133]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    901     87   John  January      Q1
1  2023-01-02       B   West    286     71   Mary  January      Q1
2  2023-01-03       C  North    130     79    Bob  January      Q1
3  2023-01-04       D  South    528     92  Alice  January      Q1
4  2023-01-05       A   East    300     57   John  January      Q1
5  2023-01-06       B   West    409     79   Mary  January      Q1
6  2023-01-07       C  North    433     44    Bob  January      Q1
7  2023-01-08       D  South    437     67  Alice  January      Q1
8  2023-01-09       A   East    200     52   John  January      Q1
9  2023-01-10       B   West    973     43   Mary  January      Q1
10 2023-01-11       C  North    280     97    Bob  January      Q1
11 2023-01-12       D  South    885     72  Alice  January      Q1
12 2023-01-13       A   East    403     52   John  January      Q1
13 2023-01-14       B   West    605     96   Mary  January      Q1
14 2023-01-15       C  North    912     98    Bob  January      Q1
15 2023-01-16       D  South    635     91  Alice  January      Q1
16 2023-01-17       A   East    492     89   John  January      Q1
17 2023-01-18       B   West    908     41   Mary  January      Q1
18 2023-01-19       C  North    146     32    Bob  January      Q1
19 2023-01-20       D  South    836     53  Alice  January      Q1

In [136]:
pd.pivot_table(df,values="Sales",index= 'Region',columns = 'Product')

Product      A      B      C      D
Region
East     459.2    NaN    NaN    NaN
North      NaN    NaN  380.2    NaN
South      NaN    NaN    NaN  664.2
West       NaN  636.2    NaN    NaN

In [137]:
pd.pivot_table(df,values="Sales",index= 'Region',columns = 'Product',aggfunc='median')

Product      A      B      C      D
Region
East     403.0    NaN    NaN    NaN
North      NaN    NaN  280.0    NaN
South      NaN    NaN    NaN  635.0
West       NaN  605.0    NaN    NaN

In [139]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index = 'Region', columns = 'Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     459.2    NaN    NaN    NaN  67.4   NaN   NaN   NaN
North      NaN    NaN  380.2    NaN   NaN   NaN  70.0   NaN
South      NaN    NaN    NaN  664.2   NaN   NaN   NaN  75.0
West       NaN  636.2    NaN    NaN   NaN  66.0   NaN   NaN

**Cross Tabs**

In [141]:
# crosstab gives counts 
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# **Operations**

**DataFrames Basic Operations**

In [142]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [143]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [144]:
df.shape

(5, 3)

In [145]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [149]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [150]:
df['A']+18

0    19
1    20
2    21
3    22
4    23
Name: A, dtype: int64

**DataFrame applying functions**

In [151]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [152]:
def square(x):
    return x**2

In [154]:
# apply keyword
df['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [158]:
# i want to apply to the original dataframe 
df['D'] = df['B'].apply(square)

In [159]:
df

   A        B    C               D
0  1    10000  100       100000000
1  2   160000  200     25600000000
2  3   810000  300    656100000000
3  4  2560000  400   6553600000000
4  5  6250000  500  39062500000000